print("Type the first number: ")
x = input()
print("Type the second number: ")
y = input()
print("x < y",x < y)
print("x > y",x > y)
print("x == y",x == y)
print("x != y",x != y)
print("x >= y",x >= y)
print("x <= y",x <= y)